# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170709_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(upload_to='dishes'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
