# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170710_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
