# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20170711_0320'),
        ('backend', '0003_auto_20170712_2123'),
    ]

    operations = [
    ]
